/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author Acer
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class KelolaData extends javax.swing.JFrame {

    /**
     * Creates new form KelolaData
     */
    private int idTerpilih = 0; // Untuk menyimpan ID paket yang mau diubah/hapus
    
    public KelolaData() {
        initComponents();
        tampilProvider();      
        tampilDataMentah();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null); 
    }
    
    private void tampilProvider() {
        try {
            comboProvider.removeAllItems();
            comboProvider.addItem("-- Pilih Provider --"); 
            Connection conn = koneksi.KoneksiDB.getKoneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nama_provider FROM Provider");
            while (rs.next()) {
                comboProvider.addItem(rs.getString("nama_provider"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat list provider: " + e.getMessage());
        }
    }
    
    public void tampilDataMentah() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Provider");
        model.addColumn("Nama Paket");
        model.addColumn("Harga");
        model.addColumn("Kuota (GB)");
        model.addColumn("Masa Aktif");
        model.addColumn("Sinyal");

        try {
            Connection conn = koneksi.KoneksiDB.getKoneksi();
            String sql = "SELECT p.id_paket, pr.nama_provider, p.nama_paket, p.harga, p.kuota_gb, p.masa_aktif_hari, p.skor_sinyal " +
                         "FROM Paket_Data p JOIN Provider pr ON p.id_provider = pr.id_provider";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_paket"),
                    rs.getString("nama_provider"),
                    rs.getString("nama_paket"),
                    rs.getInt("harga"),
                    rs.getInt("kuota_gb"),
                    rs.getInt("masa_aktif_hari"),
                    rs.getInt("skor_sinyal")
                });
            }
            tabelPaket.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboProvider = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamaPaket = new javax.swing.JTextField();
        txtHargaPaket = new javax.swing.JTextField();
        txtKuotaPaket = new javax.swing.JTextField();
        txtMasaAktifPaket = new javax.swing.JTextField();
        txtSinyalPaket = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPaket = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 248, 255));

        comboProvider.setBackground(new java.awt.Color(44, 54, 90));
        comboProvider.setEditable(true);
        comboProvider.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        comboProvider.setForeground(new java.awt.Color(239, 248, 255));
        comboProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provider:", "Telkomsel", "Indosat", "Im3", "XL", "By.U" }));
        comboProvider.setSelectedIndex(-1);
        comboProvider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboProviderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboProviderMouseExited(evt);
            }
        });
        comboProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProviderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 36, 69));
        jLabel1.setText("Nama Paket");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 36, 69));
        jLabel2.setText("Harga");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 36, 69));
        jLabel3.setText("Kuota GB");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 36, 69));
        jLabel4.setText("Masa Aktif");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 36, 69));
        jLabel5.setText("Skor Sinyal 1-5");

        txtNamaPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNamaPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNamaPaketMouseExited(evt);
            }
        });
        txtNamaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPaketActionPerformed(evt);
            }
        });

        txtHargaPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtHargaPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHargaPaketMouseExited(evt);
            }
        });
        txtHargaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaPaketActionPerformed(evt);
            }
        });

        txtKuotaPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtKuotaPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtKuotaPaketMouseExited(evt);
            }
        });
        txtKuotaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKuotaPaketActionPerformed(evt);
            }
        });

        txtMasaAktifPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMasaAktifPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMasaAktifPaketMouseExited(evt);
            }
        });
        txtMasaAktifPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasaAktifPaketActionPerformed(evt);
            }
        });

        txtSinyalPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSinyalPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSinyalPaketMouseExited(evt);
            }
        });
        txtSinyalPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSinyalPaketActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 225, 78));
        btnUbah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(44, 54, 90));
        btnUbah.setText("Ubah Data");
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahMouseExited(evt);
            }
        });
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 225, 78));
        btnHapus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(44, 54, 90));
        btnHapus.setText("Hapus Data");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(44, 54, 90));
        btnKembali.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(239, 248, 255));
        btnKembali.setText("Back");
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKembaliMouseExited(evt);
            }
        });
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(44, 54, 90));

        tabelPaket.setBackground(new java.awt.Color(239, 248, 255));
        tabelPaket.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tabelPaket.setForeground(new java.awt.Color(44, 54, 90));
        tabelPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPaketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPaket);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 36, 69));
        jLabel6.setText("Provider");

        jLabel7.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 36, 69));
        jLabel7.setText("Kelola Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtKuotaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtHargaPaket, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNamaPaket)
                                        .addComponent(comboProvider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMasaAktifPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtSinyalPaket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKuotaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMasaAktifPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSinyalPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        tampilan.MenuUtama formUtama = new tampilan.MenuUtama();
        formUtama.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (idTerpilih == 0) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data pada tabel terlebih dahulu!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin nih mau menghapus paket ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = koneksi.KoneksiDB.getKoneksi();
                String sqlDelete = "DELETE FROM Paket_Data WHERE id_paket = ?";
                PreparedStatement pst = conn.prepareStatement(sqlDelete);
                pst.setInt(1, idTerpilih);

                pst.execute();
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                tampilDataMentah(); // Refresh tabel
                idTerpilih = 0; // Reset ID
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if (idTerpilih == 0) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data pada tabel terlebih dahulu!");
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB.getKoneksi();

            // Validasi ComboBox 
            if(comboProvider.getSelectedItem() == null || comboProvider.getSelectedItem().toString().equals("-- Pilih Provider --")) {
                JOptionPane.showMessageDialog(this, "Silakan pilih Provider terlebih dahulu!");
                return; 
            }
            
            // Perbaikan SQL Injection dengan PreparedStatement
            String namaProv = comboProvider.getSelectedItem().toString();
            String sqlCariProv = "SELECT id_provider FROM Provider WHERE nama_provider = ?";
            PreparedStatement pstCari = conn.prepareStatement(sqlCariProv);
            pstCari.setString(1, namaProv);
            ResultSet rs = pstCari.executeQuery();

            if (rs.next()) {
                int idProv = rs.getInt("id_provider");

                // Query Update
                String sqlUpdate = "UPDATE Paket_Data SET id_provider=?, nama_paket=?, harga=?, kuota_gb=?, masa_aktif_hari=?, skor_sinyal=? WHERE id_paket=?";
                PreparedStatement pst = conn.prepareStatement(sqlUpdate);
                pst.setInt(1, idProv);
                pst.setString(2, txtNamaPaket.getText());
                pst.setInt(3, Integer.parseInt(txtHargaPaket.getText()));
                pst.setInt(4, Integer.parseInt(txtKuotaPaket.getText()));
                pst.setInt(5, Integer.parseInt(txtMasaAktifPaket.getText()));
                pst.setInt(6, Integer.parseInt(txtSinyalPaket.getText()));
                pst.setInt(7, idTerpilih);

                pst.execute();
                JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui!");
                tampilDataMentah(); // Refresh tabel otomatis
                idTerpilih = 0; // Reset ID
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtSinyalPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSinyalPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSinyalPaketActionPerformed

    private void txtMasaAktifPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasaAktifPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMasaAktifPaketActionPerformed

    private void txtKuotaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKuotaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKuotaPaketActionPerformed

    private void txtHargaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaPaketActionPerformed

    private void txtNamaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPaketActionPerformed

    private void comboProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProviderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProviderActionPerformed

    private void tabelPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPaketMouseClicked
        // TODO add your handling code here:
        int baris = tabelPaket.getSelectedRow();
        if (baris != -1) {
            idTerpilih = Integer.parseInt(tabelPaket.getValueAt(baris, 0).toString());
            comboProvider.setSelectedItem(tabelPaket.getValueAt(baris, 1).toString());
            txtNamaPaket.setText(tabelPaket.getValueAt(baris, 2).toString());
            txtHargaPaket.setText(tabelPaket.getValueAt(baris, 3).toString());
            txtKuotaPaket.setText(tabelPaket.getValueAt(baris, 4).toString());
            txtMasaAktifPaket.setText(tabelPaket.getValueAt(baris, 5).toString());
            txtSinyalPaket.setText(tabelPaket.getValueAt(baris, 6).toString());
        }
    }//GEN-LAST:event_tabelPaketMouseClicked

    private void txtNamaPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaPaketMouseEntered
        // TODO add your handling code here:
        txtNamaPaket.setBackground(new java.awt.Color(44,54,90));
        txtNamaPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtNamaPaketMouseEntered

    private void txtNamaPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaPaketMouseExited
        // TODO add your handling code here:
        txtNamaPaket.setBackground(new java.awt.Color(239,248,255));
        txtNamaPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtNamaPaketMouseExited

    private void txtHargaPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHargaPaketMouseEntered
        // TODO add your handling code here:
        txtHargaPaket.setBackground(new java.awt.Color(44,54,90));
        txtHargaPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtHargaPaketMouseEntered

    private void txtHargaPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHargaPaketMouseExited
        // TODO add your handling code here:
        txtHargaPaket.setBackground(new java.awt.Color(239,248,255));
        txtHargaPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtHargaPaketMouseExited

    private void txtKuotaPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKuotaPaketMouseEntered
        // TODO add your handling code here:
        txtKuotaPaket.setBackground(new java.awt.Color(44,54,90));
        txtKuotaPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtKuotaPaketMouseEntered

    private void txtKuotaPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKuotaPaketMouseExited
        // TODO add your handling code here:
        txtKuotaPaket.setBackground(new java.awt.Color(239,248,255));
        txtKuotaPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtKuotaPaketMouseExited

    private void txtMasaAktifPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasaAktifPaketMouseEntered
        // TODO add your handling code here:
        txtMasaAktifPaket.setBackground(new java.awt.Color(44,54,90));
        txtMasaAktifPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtMasaAktifPaketMouseEntered

    private void txtMasaAktifPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasaAktifPaketMouseExited
        // TODO add your handling code here:
        txtMasaAktifPaket.setBackground(new java.awt.Color(239,248,255));
        txtMasaAktifPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtMasaAktifPaketMouseExited

    private void txtSinyalPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSinyalPaketMouseEntered
        // TODO add your handling code here:
        txtSinyalPaket.setBackground(new java.awt.Color(44,54,90));
        txtSinyalPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtSinyalPaketMouseEntered

    private void txtSinyalPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSinyalPaketMouseExited
        // TODO add your handling code here:
        txtSinyalPaket.setBackground(new java.awt.Color(239,248,255));
        txtSinyalPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtSinyalPaketMouseExited

    private void btnUbahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseEntered
        // TODO add your handling code here:
        btnUbah.setBackground(new java.awt.Color(30,36,69));
        btnUbah.setForeground(new java.awt.Color(255,225,78));
    }//GEN-LAST:event_btnUbahMouseEntered

    private void btnUbahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseExited
        // TODO add your handling code here:
        btnUbah.setBackground(new java.awt.Color(255,225,78));
        btnUbah.setForeground(new java.awt.Color(30,36,69));
    }//GEN-LAST:event_btnUbahMouseExited

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        // TODO add your handling code here:
        btnHapus.setBackground(new java.awt.Color(102,0,0));
        btnHapus.setForeground(new java.awt.Color(255,225,78));
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        // TODO add your handling code here:
        btnHapus.setBackground(new java.awt.Color(255,225,78));
        btnHapus.setForeground(new java.awt.Color(30,36,69));
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnKembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseEntered
        // TODO add your handling code here:
        btnKembali.setBackground(new java.awt.Color(239,248,255));
        btnKembali.setForeground(new java.awt.Color(44,54,90));
    }//GEN-LAST:event_btnKembaliMouseEntered

    private void btnKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseExited
        // TODO add your handling code here:
        btnKembali.setBackground(new java.awt.Color(44,54,90));
        btnKembali.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_btnKembaliMouseExited

    private void comboProviderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboProviderMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProviderMouseEntered

    private void comboProviderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboProviderMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProviderMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> comboProvider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPaket;
    private javax.swing.JTextField txtHargaPaket;
    private javax.swing.JTextField txtKuotaPaket;
    private javax.swing.JTextField txtMasaAktifPaket;
    private javax.swing.JTextField txtNamaPaket;
    private javax.swing.JTextField txtSinyalPaket;
    // End of variables declaration//GEN-END:variables
}
