/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author Acer
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class KelolaData extends javax.swing.JFrame {

    /**
     * Creates new form KelolaData
     */
    private int idTerpilih = 0; // Untuk menyimpan ID paket yang mau diubah/hapus
    
    public KelolaData() {
        initComponents();
        tampilDataMentah();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null); 
    }
    
    public void tampilDataMentah() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Provider");
        model.addColumn("Nama Paket");
        model.addColumn("Harga");
        model.addColumn("Kuota (GB)");
        model.addColumn("Masa Aktif");
        model.addColumn("Sinyal");

        try {
            Connection conn = koneksi.KoneksiDB.getKoneksi();
            String sql = "SELECT p.id_paket, pr.nama_provider, p.nama_paket, p.harga, p.kuota_gb, p.masa_aktif_hari, p.skor_sinyal " +
                         "FROM Paket_Data p JOIN Provider pr ON p.id_provider = pr.id_provider";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_paket"),
                    rs.getString("nama_provider"),
                    rs.getString("nama_paket"),
                    rs.getInt("harga"),
                    rs.getInt("kuota_gb"),
                    rs.getInt("masa_aktif_hari"),
                    rs.getInt("skor_sinyal")
                });
            }
            tabelPaket.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPaket = new javax.swing.JTable();
        comboProvider = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamaPaket = new javax.swing.JTextField();
        txtHargaPaket = new javax.swing.JTextField();
        txtKuotaPaket = new javax.swing.JTextField();
        txtMasaAktifPaket = new javax.swing.JTextField();
        txtSinyalPaket = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        tabelPaket.setBackground(new java.awt.Color(0, 0, 102));
        tabelPaket.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tabelPaket.setForeground(new java.awt.Color(255, 255, 153));
        tabelPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPaketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPaket);

        comboProvider.setBackground(new java.awt.Color(0, 0, 102));
        comboProvider.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        comboProvider.setForeground(new java.awt.Color(255, 255, 153));
        comboProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provider:", "Telkomsel", "Indosat", "Im3", "XL", "By.U" }));
        comboProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProviderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Nama Paket");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Harga");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Kuota GB");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Masa Aktif");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Skor Sinyal 1-5");

        txtNamaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPaketActionPerformed(evt);
            }
        });

        txtHargaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaPaketActionPerformed(evt);
            }
        });

        txtKuotaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKuotaPaketActionPerformed(evt);
            }
        });

        txtMasaAktifPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasaAktifPaketActionPerformed(evt);
            }
        });

        txtSinyalPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSinyalPaketActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(0, 0, 102));
        btnUbah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 153));
        btnUbah.setText("Ubah Data");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(0, 0, 102));
        btnHapus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 153));
        btnHapus.setText("Hapus Data");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(13, 59, 102));
        btnKembali.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnKembali.setText("Back");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaPaket)
                                    .addComponent(txtHargaPaket)
                                    .addComponent(txtKuotaPaket)
                                    .addComponent(txtMasaAktifPaket)
                                    .addComponent(txtSinyalPaket)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKuotaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMasaAktifPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSinyalPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if (idTerpilih == 0) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data pada tabel terlebih dahulu!");
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB.getKoneksi();

            // Cari id_provider berdasarkan nama di ComboBox
            String namaProv = comboProvider.getSelectedItem().toString();
            String sqlCariProv = "SELECT id_provider FROM Provider WHERE nama_provider = '" + namaProv + "'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sqlCariProv);

            if (rs.next()) {
                int idProv = rs.getInt("id_provider");

                // Query Update
                String sqlUpdate = "UPDATE Paket_Data SET id_provider=?, nama_paket=?, harga=?, kuota_gb=?, masa_aktif_hari=?, skor_sinyal=? WHERE id_paket=?";
                PreparedStatement pst = conn.prepareStatement(sqlUpdate);
                pst.setInt(1, idProv);
                pst.setString(2, txtNamaPaket.getText());
                pst.setInt(3, Integer.parseInt(txtHargaPaket.getText()));
                pst.setInt(4, Integer.parseInt(txtKuotaPaket.getText()));
                pst.setInt(5, Integer.parseInt(txtMasaAktifPaket.getText()));
                pst.setInt(6, Integer.parseInt(txtSinyalPaket.getText()));
                pst.setInt(7, idTerpilih);

                pst.execute();
                JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui!");
                tampilDataMentah(); // Refresh tabel otomatis
                idTerpilih = 0; // Reset ID
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (idTerpilih == 0) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data pada tabel terlebih dahulu!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin nih mau menghapus paket ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = koneksi.KoneksiDB.getKoneksi();
                String sqlDelete = "DELETE FROM Paket_Data WHERE id_paket = ?";
                PreparedStatement pst = conn.prepareStatement(sqlDelete);
                pst.setInt(1, idTerpilih);

                pst.execute();
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                tampilDataMentah(); // Refresh tabel
                idTerpilih = 0; // Reset ID
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void comboProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProviderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProviderActionPerformed

    private void txtNamaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPaketActionPerformed

    private void txtHargaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaPaketActionPerformed

    private void txtKuotaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKuotaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKuotaPaketActionPerformed

    private void txtMasaAktifPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasaAktifPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMasaAktifPaketActionPerformed

    private void txtSinyalPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSinyalPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSinyalPaketActionPerformed

    private void tabelPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPaketMouseClicked
        // TODO add your handling code here:
        int baris = tabelPaket.getSelectedRow();
        if (baris != -1) {
            idTerpilih = Integer.parseInt(tabelPaket.getValueAt(baris, 0).toString());
            comboProvider.setSelectedItem(tabelPaket.getValueAt(baris, 1).toString());
            txtNamaPaket.setText(tabelPaket.getValueAt(baris, 2).toString());
            txtHargaPaket.setText(tabelPaket.getValueAt(baris, 3).toString());
            txtKuotaPaket.setText(tabelPaket.getValueAt(baris, 4).toString());
            txtMasaAktifPaket.setText(tabelPaket.getValueAt(baris, 5).toString());
            txtSinyalPaket.setText(tabelPaket.getValueAt(baris, 6).toString());
}
    }//GEN-LAST:event_tabelPaketMouseClicked

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        tampilan.MenuUtama formUtama = new tampilan.MenuUtama();
        formUtama.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> comboProvider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPaket;
    private javax.swing.JTextField txtHargaPaket;
    private javax.swing.JTextField txtKuotaPaket;
    private javax.swing.JTextField txtMasaAktifPaket;
    private javax.swing.JTextField txtNamaPaket;
    private javax.swing.JTextField txtSinyalPaket;
    // End of variables declaration//GEN-END:variables
}
