/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author Acer
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtKuota = new javax.swing.JTextField();
        txtMasaAktif = new javax.swing.JTextField();
        txtSinyal = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHasil = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btntambahpaket = new javax.swing.JButton();
        btnkeloladata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Bobot Harga (%)");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Bobot Kuota (%)");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Bobot Masa Aktif (%)");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Bobot Sinyal (%)");

        txtMasaAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasaAktifActionPerformed(evt);
            }
        });

        txtSinyal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSinyalActionPerformed(evt);
            }
        });

        btnHitung.setBackground(new java.awt.Color(0, 0, 102));
        btnHitung.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 153));
        btnHitung.setText("Hitung Rekomendasi");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        tabelHasil.setBackground(new java.awt.Color(0, 0, 102));
        tabelHasil.setForeground(new java.awt.Color(255, 255, 153));
        tabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelHasil);

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Kuota Match");

        btntambahpaket.setBackground(new java.awt.Color(0, 0, 102));
        btntambahpaket.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btntambahpaket.setForeground(new java.awt.Color(255, 255, 153));
        btntambahpaket.setText("Tambah Paket Baru");
        btntambahpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahpaketActionPerformed(evt);
            }
        });

        btnkeloladata.setBackground(new java.awt.Color(0, 0, 102));
        btnkeloladata.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnkeloladata.setForeground(new java.awt.Color(255, 255, 153));
        btnkeloladata.setText("Kelola Data");
        btnkeloladata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeloladataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMasaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(48, 48, 48)
                            .addComponent(txtKuota, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSinyal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btntambahpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnHitung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnkeloladata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(372, 372, 372))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMasaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSinyal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHitung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btntambahpaket))
                            .addComponent(btnkeloladata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSinyalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSinyalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSinyalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil input bobot secara mentah dulu
            double inputHarga = Double.parseDouble(txtHarga.getText());
            double inputKuota = Double.parseDouble(txtKuota.getText());
            double inputMasa = Double.parseDouble(txtMasaAktif.getText());
            double inputSinyal = Double.parseDouble(txtSinyal.getText());

            // Validasi: Total bobot mentah harus pas 100
            if ((inputHarga + inputKuota + inputMasa + inputSinyal) != 100.0) {
                JOptionPane.showMessageDialog(this, "Total bobot harus pas 100% lho!");
                return;
            }

            // Kalau sudah pas 100, baru kita bagi 100.0 untuk perhitungan SAW (menjadi 0.4, 0.3, dst)
            double bHarga = inputHarga / 100.0;
            double bKuota = inputKuota / 100.0;
            double bMasa = inputMasa / 100.0;
            double bSinyal = inputSinyal / 100.0;

            // Panggil koneksi database dari package sebelah
            Connection conn = koneksi.KoneksiDB.getKoneksi();
            Statement st = conn.createStatement();

            // 2. Cari Nilai Max (Benefit) dan Min (Cost) dari Database
            String sqlMaxMin = "SELECT MIN(harga) as min_harga, MAX(kuota_gb) as max_kuota, MAX(masa_aktif_hari) as max_masa, MAX(skor_sinyal) as max_sinyal FROM Paket_Data";
            ResultSet rsMaxMin = st.executeQuery(sqlMaxMin);
            rsMaxMin.next();

            double minHarga = rsMaxMin.getDouble("min_harga");
            double maxKuota = rsMaxMin.getDouble("max_kuota");
            double maxMasa = rsMaxMin.getDouble("max_masa");
            double maxSinyal = rsMaxMin.getDouble("max_sinyal");

            // 3. Ambil semua data paket untuk dihitung normalisasinya
            String sqlData = "SELECT p.nama_paket, pr.nama_provider, p.harga, p.kuota_gb, p.masa_aktif_hari, p.skor_sinyal " +
                             "FROM Paket_Data p JOIN Provider pr ON p.id_provider = pr.id_provider";
            ResultSet rsData = st.executeQuery(sqlData);

            // Siapkan list sementara untuk menyimpan hasil perhitungan sebelum diurutkan
            ArrayList<Object[]> listHasil = new ArrayList<>();

            while (rsData.next()) {
                String namaPaket = rsData.getString("nama_provider") + " - " + rsData.getString("nama_paket");
                double harga = rsData.getDouble("harga");
                double kuota = rsData.getDouble("kuota_gb");
                double masa = rsData.getDouble("masa_aktif_hari");
                double sinyal = rsData.getDouble("skor_sinyal");

                // Proses Normalisasi SAW
                double normHarga = minHarga / harga;         // Sifat Cost
                double normKuota = kuota / maxKuota;         // Sifat Benefit
                double normMasa = masa / maxMasa;            // Sifat Benefit
                double normSinyal = sinyal / maxSinyal;      // Sifat Benefit

                // Hitung Skor Akhir Preferensi (V)
                double skorAkhir = (normHarga * bHarga) + (normKuota * bKuota) + (normMasa * bMasa) + (normSinyal * bSinyal);

                listHasil.add(new Object[]{namaPaket, skorAkhir});
            }

            // 4. Urutkan hasil dari skor tertinggi ke terendah (Peringkat 1 di atas)
            Collections.sort(listHasil, new Comparator<Object[]>() {
                public int compare(Object[] o1, Object[] o2) {
                    return Double.compare((Double) o2[1], (Double) o1[1]);
                }
            });

            // 5. Tampilkan hasilnya ke dalam JTable
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Peringkat");
            model.addColumn("Nama Provider & Paket");
            model.addColumn("Skor Rekomendasi");

            int peringkat = 1;
            for (Object[] baris : listHasil) {
                // Format angka skor agar rapi (3 angka di belakang koma)
                String skorFormat = String.format("%.3f", (Double) baris[1]);
                model.addRow(new Object[]{peringkat++, baris[0], skorFormat});
            }

            tabelHasil.setModel(model);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Pastikan semua kotak diisi dengan angka saja ya!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
}
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btntambahpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahpaketActionPerformed
        // TODO add your handling code here:
        // Membuka frame TambahData
        tampilan.TambahData formTambah = new tampilan.TambahData();
        formTambah.setVisible(true);
        formTambah.setLocationRelativeTo(this); // Biar munculnya pas di tengah layar
    }//GEN-LAST:event_btntambahpaketActionPerformed

    private void txtMasaAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasaAktifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMasaAktifActionPerformed

    private void btnkeloladataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeloladataActionPerformed
        // TODO add your handling code here:
        tampilan.KelolaData formKelola = new tampilan.KelolaData();
        formKelola.setVisible(true);
        formKelola.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnkeloladataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnkeloladata;
    private javax.swing.JButton btntambahpaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelHasil;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKuota;
    private javax.swing.JTextField txtMasaAktif;
    private javax.swing.JTextField txtSinyal;
    // End of variables declaration//GEN-END:variables
}
