/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author Acer
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JFrame;

public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null); 
        

        jMenuBar1.setUI(new javax.swing.plaf.basic.BasicMenuBarUI());
        jMenuBar1.setBackground(new java.awt.Color(30, 36, 69));

        tambah_paket_baru.setBackground(new java.awt.Color(30,36,69));
        tambah_paket_baru.setForeground(new java.awt.Color(255,225,78));

        kelola_data.setBackground(new java.awt.Color(30,36,69));
        kelola_data.setForeground(new java.awt.Color(255,225,78));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtKuota = new javax.swing.JTextField();
        txtMasaAktif = new javax.swing.JTextField();
        txtSinyal = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHasil = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        tambah_paket_baru = new javax.swing.JMenuItem();
        kelola_data = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 248, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 36, 69));
        jLabel1.setText("Bobot Harga (%)");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 36, 69));
        jLabel2.setText("Bobot Kuota (%)");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 36, 69));
        jLabel3.setText("Bobot Masa Aktif (%)");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 36, 69));
        jLabel4.setText("Bobot Sinyal (%)");

        txtHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtHargaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHargaMouseExited(evt);
            }
        });
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        txtKuota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtKuotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtKuotaMouseExited(evt);
            }
        });

        txtMasaAktif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMasaAktifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMasaAktifMouseExited(evt);
            }
        });
        txtMasaAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasaAktifActionPerformed(evt);
            }
        });

        txtSinyal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSinyalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSinyalMouseExited(evt);
            }
        });
        txtSinyal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSinyalActionPerformed(evt);
            }
        });

        btnHitung.setBackground(new java.awt.Color(255, 225, 78));
        btnHitung.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(30, 36, 39));
        btnHitung.setText("Hitung Rekomendasi");
        btnHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHitungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHitungMouseExited(evt);
            }
        });
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 36, 69));
        jLabel5.setText("Kuota Match");

        jPanel2.setBackground(new java.awt.Color(44, 54, 90));

        tabelHasil.setBackground(new java.awt.Color(239, 248, 255));
        tabelHasil.setForeground(new java.awt.Color(0, 0, 102));
        tabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelHasil);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSinyal)
                                .addComponent(txtHarga)
                                .addComponent(txtKuota)
                                .addComponent(txtMasaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKuota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMasaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSinyal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, txtHarga, txtKuota, txtMasaAktif, txtSinyal});

        jMenuBar1.setBackground(new java.awt.Color(239, 248, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setOpaque(true);

        jMenu1.setBackground(new java.awt.Color(30, 36, 69));
        jMenu1.setForeground(new java.awt.Color(239, 248, 255));
        jMenu1.setText("☰");
        jMenu1.setOpaque(true);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu1MouseExited(evt);
            }
        });

        tambah_paket_baru.setBackground(new java.awt.Color(0, 0, 102));
        tambah_paket_baru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tambah_paket_baru.setForeground(new java.awt.Color(239, 248, 255));
        tambah_paket_baru.setText("Tambah Paket Baru");
        tambah_paket_baru.setOpaque(true);
        tambah_paket_baru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambah_paket_baruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambah_paket_baruMouseExited(evt);
            }
        });
        tambah_paket_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_paket_baruActionPerformed(evt);
            }
        });
        jMenu1.add(tambah_paket_baru);

        kelola_data.setBackground(new java.awt.Color(0, 0, 102));
        kelola_data.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kelola_data.setForeground(new java.awt.Color(239, 248, 255));
        kelola_data.setText("Kelola Data");
        kelola_data.setOpaque(true);
        kelola_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kelola_dataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kelola_dataMouseExited(evt);
            }
        });
        kelola_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelola_dataActionPerformed(evt);
            }
        });
        jMenu1.add(kelola_data);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSinyalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSinyalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSinyalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil input bobot secara mentah dulu
            double inputHarga = Double.parseDouble(txtHarga.getText());
            double inputKuota = Double.parseDouble(txtKuota.getText());
            double inputMasa = Double.parseDouble(txtMasaAktif.getText());
            double inputSinyal = Double.parseDouble(txtSinyal.getText());

            // Validasi: Total bobot mentah harus pas 100
            if ((inputHarga + inputKuota + inputMasa + inputSinyal) != 100.0) {
                JOptionPane.showMessageDialog(this, "Total bobot harus pas 100% lho!");
                return;
            }

            // Kalau sudah pas 100, baru kita bagi 100.0 untuk perhitungan SAW
            double bHarga = inputHarga / 100.0;
            double bKuota = inputKuota / 100.0;
            double bMasa = inputMasa / 100.0;
            double bSinyal = inputSinyal / 100.0;

            Connection conn = koneksi.KoneksiDB.getKoneksi();
            Statement st = conn.createStatement();

            // 2. Cari Nilai Max (Benefit) dan Min (Cost) dari Database
            String sqlMaxMin = "SELECT MIN(harga) as min_harga, MAX(kuota_gb) as max_kuota, MAX(masa_aktif_hari) as max_masa, MAX(skor_sinyal) as max_sinyal FROM Paket_Data";
            ResultSet rsMaxMin = st.executeQuery(sqlMaxMin);
            
            // Cek jika database kosong agar tidak crash
            if (!rsMaxMin.next() || rsMaxMin.getObject("min_harga") == null) {
                JOptionPane.showMessageDialog(this, "Data paket masih kosong nih! Silakan tambah data paket dulu ya.");
                return;
            }

            double minHarga = rsMaxMin.getDouble("min_harga");
            double maxKuota = rsMaxMin.getDouble("max_kuota");
            double maxMasa = rsMaxMin.getDouble("max_masa");
            double maxSinyal = rsMaxMin.getDouble("max_sinyal");

            // 3. Ambil semua data paket untuk dihitung normalisasinya
            String sqlData = "SELECT p.nama_paket, pr.nama_provider, p.harga, p.kuota_gb, p.masa_aktif_hari, p.skor_sinyal " +
                             "FROM Paket_Data p JOIN Provider pr ON p.id_provider = pr.id_provider";
            ResultSet rsData = st.executeQuery(sqlData);

            ArrayList<Object[]> listHasil = new ArrayList<>();

            while (rsData.next()) {
                String namaPaket = rsData.getString("nama_provider") + " - " + rsData.getString("nama_paket");
                double harga = rsData.getDouble("harga");
                double kuota = rsData.getDouble("kuota_gb");
                double masa = rsData.getDouble("masa_aktif_hari");
                double sinyal = rsData.getDouble("skor_sinyal");

                // Proses Normalisasi SAW
                double normHarga = minHarga / harga;         
                double normKuota = kuota / maxKuota;         
                double normMasa = masa / maxMasa;            
                double normSinyal = sinyal / maxSinyal;      

                // Hitung Skor Akhir Preferensi (V)
                double skorAkhir = (normHarga * bHarga) + (normKuota * bKuota) + (normMasa * bMasa) + (normSinyal * bSinyal);

                listHasil.add(new Object[]{namaPaket, skorAkhir});
            }

            // 4. Urutkan hasil dari skor tertinggi ke terendah
            Collections.sort(listHasil, new Comparator<Object[]>() {
                public int compare(Object[] o1, Object[] o2) {
                    return Double.compare((Double) o2[1], (Double) o1[1]);
                }
            });

            // 5. Tampilkan hasilnya ke dalam JTable
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Peringkat");
            model.addColumn("Nama Provider & Paket");
            model.addColumn("Skor Rekomendasi");

            int peringkat = 1;
            for (Object[] baris : listHasil) {
                String skorFormat = String.format("%.3f", (Double) baris[1]);
                model.addRow(new Object[]{peringkat++, baris[0], skorFormat});
            }

            tabelHasil.setModel(model);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Pastikan semua kotak bobot diisi dengan angka saja ya!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtMasaAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasaAktifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMasaAktifActionPerformed

    private void txtHargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHargaMouseEntered
        // TODO add your handling code here:
        txtHarga.setBackground(new java.awt.Color(44,54,90));
        txtHarga.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtHargaMouseEntered

    private void txtKuotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKuotaMouseEntered
        // TODO add your handling code here:
        txtKuota.setBackground(new java.awt.Color(44,54,90));
        txtKuota.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtKuotaMouseEntered

    private void txtMasaAktifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasaAktifMouseEntered
        // TODO add your handling code here:
        txtMasaAktif.setBackground(new java.awt.Color(44,54,90));
        txtMasaAktif.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtMasaAktifMouseEntered

    private void txtSinyalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSinyalMouseEntered
        // TODO add your handling code here:
        txtSinyal.setBackground(new java.awt.Color(44,54,90));
        txtSinyal.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtSinyalMouseEntered

    private void txtHargaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHargaMouseExited
        // TODO add your handling code here:
        txtHarga.setBackground(new java.awt.Color(239,248,255));
        txtHarga.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtHargaMouseExited

    private void txtKuotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKuotaMouseExited
        // TODO add your handling code here:
        txtKuota.setBackground(new java.awt.Color(239,248,255));
        txtKuota.setForeground(new java.awt.Color(30,36,69));
    }//GEN-LAST:event_txtKuotaMouseExited

    private void txtMasaAktifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasaAktifMouseExited
        // TODO add your handling code here:
        txtMasaAktif.setBackground(new java.awt.Color(239,248,255));
        txtMasaAktif.setForeground(new java.awt.Color(30,36,69));
    }//GEN-LAST:event_txtMasaAktifMouseExited

    private void txtSinyalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSinyalMouseExited
        // TODO add your handling code here:
        txtSinyal.setBackground(new java.awt.Color(239,248,255));
        txtSinyal.setForeground(new java.awt.Color(30,36,69));
    }//GEN-LAST:event_txtSinyalMouseExited

    private void btnHitungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseEntered
        // TODO add your handling code here:
        btnHitung.setBackground(new java.awt.Color(30,36,69));
        btnHitung.setForeground(new java.awt.Color(255,225,78));
    }//GEN-LAST:event_btnHitungMouseEntered

    private void btnHitungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseExited
        // TODO add your handling code here:
        btnHitung.setBackground(new java.awt.Color(255,225,78));
        btnHitung.setForeground(new java.awt.Color(30,36,69));
    }//GEN-LAST:event_btnHitungMouseExited

    private void jMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseExited
        // TODO add your handling code here:
        jMenu1.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_jMenu1MouseExited

    private void jMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseEntered
        // TODO add your handling code here:
        jMenu1.setForeground(new java.awt.Color(255,225,78));
    }//GEN-LAST:event_jMenu1MouseEntered

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        jMenu1.setBackground(new java.awt.Color(239,248,255));
        jMenu1.setBackground(new java.awt.Color(0, 0, 102));
    }//GEN-LAST:event_jMenu1MouseClicked

    private void kelola_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelola_dataActionPerformed
        // TODO add your handling code here:
        tampilan.KelolaData formKelola = new tampilan.KelolaData();
        formKelola.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_kelola_dataActionPerformed

    private void kelola_dataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelola_dataMouseExited
        // TODO add your handling code here:
        kelola_data.setBackground(new java.awt.Color(30,36,69));
        kelola_data.setForeground(new java.awt.Color(255,225,78));
    }//GEN-LAST:event_kelola_dataMouseExited

    private void kelola_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelola_dataMouseEntered
        // TODO add your handling code here:
        kelola_data.setBackground(new java.awt.Color(255,225,78));
        kelola_data.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_kelola_dataMouseEntered

    private void tambah_paket_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_paket_baruActionPerformed
        // TODO add your handling code here:
        tampilan.TambahData formTambah = new tampilan.TambahData();
        formTambah.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_tambah_paket_baruActionPerformed

    private void tambah_paket_baruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_paket_baruMouseExited
        // TODO add your handling code here:
        tambah_paket_baru.setBackground(new java.awt.Color(30,36,69));
        tambah_paket_baru.setForeground(new java.awt.Color(255,225,78));
    }//GEN-LAST:event_tambah_paket_baruMouseExited

    private void tambah_paket_baruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_paket_baruMouseEntered
        // TODO add your handling code here:
        tambah_paket_baru.setBackground(new java.awt.Color(255,225,78));
        tambah_paket_baru.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_tambah_paket_baruMouseEntered

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem kelola_data;
    private javax.swing.JTable tabelHasil;
    private javax.swing.JMenuItem tambah_paket_baru;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKuota;
    private javax.swing.JTextField txtMasaAktif;
    private javax.swing.JTextField txtSinyal;
    // End of variables declaration//GEN-END:variables
}
