/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author Acer
 */

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class TambahData extends javax.swing.JFrame {

    /**
     * Creates new form TambahData
     */
    public TambahData() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboProvider = new javax.swing.JComboBox<>();
        txtNamaPaket = new javax.swing.JTextField();
        txtHargaPaket = new javax.swing.JTextField();
        txtKuotaPaket = new javax.swing.JTextField();
        txtMasaAktifPaket = new javax.swing.JTextField();
        txtSinyalPaket = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 248, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 153));

        comboProvider.setBackground(new java.awt.Color(44, 54, 90));
        comboProvider.setEditable(true);
        comboProvider.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        comboProvider.setForeground(new java.awt.Color(239, 248, 255));
        comboProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telkomsel", "IM3", "Tri", "XL", "By.U", " " }));
        comboProvider.setSelectedIndex(-1);
        comboProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProviderActionPerformed(evt);
            }
        });

        txtNamaPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNamaPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNamaPaketMouseExited(evt);
            }
        });

        txtHargaPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtHargaPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHargaPaketMouseExited(evt);
            }
        });

        txtKuotaPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtKuotaPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtKuotaPaketMouseExited(evt);
            }
        });
        txtKuotaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKuotaPaketActionPerformed(evt);
            }
        });

        txtMasaAktifPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMasaAktifPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMasaAktifPaketMouseExited(evt);
            }
        });

        txtSinyalPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSinyalPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSinyalPaketMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 36, 69));
        jLabel1.setText("Nama Paket");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 36, 69));
        jLabel2.setText("Harga");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 36, 69));
        jLabel3.setText("Kuota GB");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 36, 69));
        jLabel4.setText("Masa Aktif");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 36, 69));
        jLabel5.setText("Skor Sinyal 1-5");

        btnSimpan.setBackground(new java.awt.Color(255, 225, 78));
        btnSimpan.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(44, 54, 90));
        btnSimpan.setText("Simpan Data");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpanMouseExited(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(44, 54, 90));
        btnKembali.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(239, 248, 255));
        btnKembali.setText("Back");
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKembaliMouseExited(evt);
            }
        });
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 36, 69));
        jLabel6.setText("Provider");

        jPanel2.setBackground(new java.awt.Color(44, 54, 90));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 36, 69));
        jLabel7.setText("Tambah Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMasaAktifPaket, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtKuotaPaket, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHargaPaket, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNamaPaket, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboProvider, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSinyalPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKuotaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMasaAktifPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSinyalPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(40, 40, 40)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        tampilan.MenuUtama formUtama = new tampilan.MenuUtama();
        formUtama.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = koneksi.KoneksiDB.getKoneksi();

            // 1. Ambil nama provider dari ComboBox dan cari id_provider-nya di database
            String namaProv = comboProvider.getSelectedItem().toString();
            String sqlCariProv = "SELECT id_provider FROM Provider WHERE nama_provider = '" + namaProv + "'";

            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sqlCariProv);

            if(rs.next()) {
                int idProv = rs.getInt("id_provider");

                // 2. Siapkan perintah INSERT ke tabel Paket_Data
                String sqlInsert = "INSERT INTO Paket_Data (id_provider, nama_paket, harga, kuota_gb, masa_aktif_hari, skor_sinyal) VALUES (?, ?, ?, ?, ?, ?)";

                PreparedStatement pst = conn.prepareStatement(sqlInsert);
                pst.setInt(1, idProv);
                pst.setString(2, txtNamaPaket.getText());
                pst.setInt(3, Integer.parseInt(txtHargaPaket.getText()));
                pst.setInt(4, Integer.parseInt(txtKuotaPaket.getText()));
                pst.setInt(5, Integer.parseInt(txtMasaAktifPaket.getText()));
                pst.setInt(6, Integer.parseInt(txtSinyalPaket.getText()));

                // 3. Eksekusi penyimpanan
                pst.execute();
                JOptionPane.showMessageDialog(this, "Mantap! Data Paket Baru Berhasil Ditambahkan.");

                // Opsi: Tutup jendela ini setelah selesai menyimpan
                this.dispose();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Periksa lagi! Harga, Kuota, Masa Aktif, dan Sinyal harus diisi dengan angka.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtKuotaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKuotaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKuotaPaketActionPerformed

    private void comboProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProviderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProviderActionPerformed

    private void txtNamaPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaPaketMouseEntered
        // TODO add your handling code here:
        txtNamaPaket.setBackground(new java.awt.Color(44,54,90));
        txtNamaPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtNamaPaketMouseEntered

    private void txtNamaPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaPaketMouseExited
        // TODO add your handling code here:
        txtNamaPaket.setBackground(new java.awt.Color(239,248,255));
        txtNamaPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtNamaPaketMouseExited

    private void txtHargaPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHargaPaketMouseEntered
        // TODO add your handling code here:
        txtHargaPaket.setBackground(new java.awt.Color(44,54,90));
        txtHargaPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtHargaPaketMouseEntered

    private void txtHargaPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHargaPaketMouseExited
        // TODO add your handling code here:
        txtHargaPaket.setBackground(new java.awt.Color(239,248,255));
        txtHargaPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtHargaPaketMouseExited

    private void txtKuotaPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKuotaPaketMouseEntered
        // TODO add your handling code here:
        txtKuotaPaket.setBackground(new java.awt.Color(44,54,90));
        txtKuotaPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtKuotaPaketMouseEntered

    private void txtKuotaPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKuotaPaketMouseExited
        // TODO add your handling code here:
        txtKuotaPaket.setBackground(new java.awt.Color(239,248,255));
        txtKuotaPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtKuotaPaketMouseExited

    private void txtMasaAktifPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasaAktifPaketMouseEntered
        // TODO add your handling code here:
        txtMasaAktifPaket.setBackground(new java.awt.Color(44,54,90));
        txtMasaAktifPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtMasaAktifPaketMouseEntered

    private void txtMasaAktifPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasaAktifPaketMouseExited
        // TODO add your handling code here:
        txtMasaAktifPaket.setBackground(new java.awt.Color(239,248,255));
        txtMasaAktifPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtMasaAktifPaketMouseExited

    private void txtSinyalPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSinyalPaketMouseEntered
        // TODO add your handling code here:
        txtSinyalPaket.setBackground(new java.awt.Color(44,54,90));
        txtSinyalPaket.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_txtSinyalPaketMouseEntered

    private void txtSinyalPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSinyalPaketMouseExited
        // TODO add your handling code here:
        txtSinyalPaket.setBackground(new java.awt.Color(239,248,255));
        txtSinyalPaket.setForeground(new java.awt.Color(30,36,39));
    }//GEN-LAST:event_txtSinyalPaketMouseExited

    private void btnSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseEntered
        // TODO add your handling code here:
        btnSimpan.setBackground(new java.awt.Color(30,36,69));
        btnSimpan.setForeground(new java.awt.Color(255,225,78));
    }//GEN-LAST:event_btnSimpanMouseEntered

    private void btnSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseExited
        // TODO add your handling code here:
        btnSimpan.setBackground(new java.awt.Color(255,225,78));
        btnSimpan.setForeground(new java.awt.Color(30,36,69));
    }//GEN-LAST:event_btnSimpanMouseExited

    private void btnKembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseEntered
        // TODO add your handling code here:
        btnKembali.setBackground(new java.awt.Color(239,248,255));
        btnKembali.setForeground(new java.awt.Color(44,54,90));
    }//GEN-LAST:event_btnKembaliMouseEntered

    private void btnKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseExited
        // TODO add your handling code here:
        btnKembali.setBackground(new java.awt.Color(44,54,90));
        btnKembali.setForeground(new java.awt.Color(239,248,255));
    }//GEN-LAST:event_btnKembaliMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> comboProvider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtHargaPaket;
    private javax.swing.JTextField txtKuotaPaket;
    private javax.swing.JTextField txtMasaAktifPaket;
    private javax.swing.JTextField txtNamaPaket;
    private javax.swing.JTextField txtSinyalPaket;
    // End of variables declaration//GEN-END:variables
}
